In [1]:
import numpy as np

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
arr1 = np.arange(2,51,3)
print(arr1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
l1 = list(map(int,input().split()))
l2 = list(map(int,input().split()))
arr1 = np.array(l1)
arr2 = np.array(l2)
arr3 = np.concatenate((arr1,arr2))
print("Array after Concatenation:",arr3)
print("Sorted:",np.sort(arr3))

1 3 5 7 9
2 4 6 8 10
Array after Concatenation: [ 1  3  5  7  9  2  4  6  8 10]
Sorted: [ 1  2  3  4  5  6  7  8  9 10]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr1 = np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
print(arr1)
print("Dimension:",arr1.ndim)
print("Size:",arr1.size)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimension: 2
Size: 12


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

Ans: To convert a 1D array into 2D array numpy functions can be used like expand_dims,newaxis and reshape. Given below are all the three implementations

In [5]:
arr1 = np.arange(1,13)
print("Dimension of array 1:",arr1.ndim)
arr2 = np.expand_dims(arr1, 1)
print("Dimension of Array 2:",arr2.ndim)
arr3 = arr1[np.newaxis]
print("Dimension of Array 3:",arr3.ndim)
arr4 = arr1.reshape(-1,2)
print("Dimension of Array 4:",arr4.ndim)

Dimension of array 1: 1
Dimension of Array 2: 2
Dimension of Array 3: 2
Dimension of Array 4: 2


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
arr1 = np.arange(1,10).reshape(3,3)
print("Array 1:")
print(arr1)
arr2 = np.arange(10,19).reshape(3,3)
print("Array 2:")
print(arr2)
arr3 = np.vstack((arr1,arr2))
print("Array 3(Vertical):")
print(arr3)
arr4 = np.hstack((arr1,arr2))
print("Array 4(Horizontal):")
print(arr4)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Array 3(Vertical):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Array 4(Horizontal):
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


# Questions 6:
How to get unique items and counts of unique items?

In [7]:
arr1 = np.array([1,3,5,2,5,7,4,8,9,5,8,4,2,7,4])
unique, unique_count = np.unique(arr1,return_counts=True)
print("Unique Elements:", unique)
print("Unique Count:   ",unique_count)

Unique Elements: [1 2 3 4 5 7 8 9]
Unique Count:    [1 2 1 3 3 2 2 1]
